# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/muneebgrad',
                'doc_host': 'https://moneebullah25.github.io',
                'git_url': 'https://github.com/moneebullah25/muneebgrad',
                'lib_path': 'muneebgrad'},
  'syms': {'muneebgrad.core': {'muneebgrad.core.foo': ('core.html#foo', 'muneebgrad/core.py')}}}
